included:
  - ios

excluded:
  - Pods

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - modifier_order
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

disabled_rules:
  - trailing_comma
  - identifier_name
  - type_name
  - missing_docs

line_length:
  warning: 150
  error: 200

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 130
  error: 200

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3

reporter: "xcode"
